import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { FiDownload } from "react-icons/fi";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";

export default function ReportScreen() {
  const navigate = useNavigate();
  const [reportHTML, setReportHTML] = useState("");
  const [patientName, setPatientName] = useState("Not specified");
  const [patientAge, setPatientAge] = useState("Not specified");
  const [diagnosisType, setDiagnosisType] = useState("Not specified");
  const [reportDate, setReportDate] = useState(new Date().toLocaleDateString());
  const [showSections, setShowSections] = useState({
    summary: true,
    prescription: true,
    diagnosis: true,
    treatment: true,
    caseManagement: true,
  });
  const reportRef = useRef();

  useEffect(() => {
    const saved = localStorage.getItem("finalReportHTML");
    if (saved) {
      setReportHTML(saved);

      const extractFromText = (label) => {
        const regex = new RegExp(`${label}:\\s*(.*?)\\n`, "i");
        const match = saved.match(regex);
        return match ? match[1].trim() : "Not specified";
      };

      setPatientName(extractFromText("Patient Name"));
      setPatientAge(extractFromText("Patient Age"));
      setDiagnosisType(extractFromText("Diagnosis Type"));
    }
  }, []);

  const formatSection = (title, icon, content, key) => {
    return `
      <section style="margin-bottom: 2rem;">
        <h2 style="font-size: 1.2rem; font-weight: 600; color: #a78bfa; margin-bottom: 0.5rem; cursor: pointer;" onclick="document.getElementById('${key}').classList.toggle('hidden')">${icon} ${title}</h2>
        <div id="${key}">${content}</div>
      </section>
    `;
  };

  const extractSection = (heading) => {
    const regex = new RegExp(`<h2[^>]*>${heading}<\\/h2>([\\s\\S]*?)(?=<h2|<\\/body|$)`, "i");
    const match = reportHTML.match(regex);
    if (match && match[1].trim()) {
      return `<div>${match[1].trim()}</div>`;
    }
    return "<p>Not available.</p>";
  };

  const sectionedHTML = `
    ${formatSection("Patient Information", "🧍", `
      <p><strong>Name:</strong> ${patientName}</p>
      <p><strong>Age:</strong> ${patientAge}</p>
      <p><strong>Date:</strong> ${reportDate}</p>
    `, "patient-info")}
    ${showSections.summary ? formatSection("Summary", "📋", extractSection("Patient Summary"), "summary") : ""}
    ${showSections.prescription ? formatSection("Prescription", "💊", extractSection("Rx (Potential Prescription Considerations)"), "prescription") : ""}
    ${showSections.diagnosis ? formatSection("Diagnosis", "🧬", extractSection("Dx (Potential Differential Diagnoses)"), "diagnosis") : ""}
    ${showSections.treatment ? formatSection("Treatment Plan", "🧪", extractSection("Tx (Potential Treatment Approaches)"), "treatment") : ""}
    ${showSections.caseManagement ? formatSection("Case Management Steps", "📈", extractSection("Possible Case Management Steps"), "case-management") : ""}
  `;

  const handleDownloadPDF = async () => {
    if (!reportRef.current) return;
    const reportWindow = window.open('', '_blank');
    const html = `
      <html>
        <head>
          <title>Report for ${patientName}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 2rem; }
            h1 { color: #ec4899; font-size: 24px; }
            h2 { color: #8b5cf6; font-size: 18px; margin-top: 1.5rem; }
            p, li { font-size: 14px; line-height: 1.6; }
          </style>
        </head>
        <body>
          <h1>🧠 Preliminary Medical Report</h1>
          <p><em>Generated by HimalAI for <strong>${patientName}</strong> on ${reportDate}</em></p>
          ${sectionedHTML}
          <footer style="margin-top: 2rem; font-size: 12px; color: gray;">
            📌 This is a preliminary report. All recommendations must be verified clinically.
          </footer>
        </body>
      </html>
    `;
    reportWindow.document.write(html);
    reportWindow.document.close();
    reportWindow.focus();
    reportWindow.print();
  };

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white px-4 py-10">
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex justify-center gap-10 text-sm text-gray-400 mb-8 border-b border-white/10 pb-2 w-full max-w-3xl mx-auto"
      >
        <button onClick={() => navigate("/chat")} className="hover:text-white transition">Chat</button>
        <button className="border-b-2 border-white text-white pb-1">Report</button>
        <button
          onClick={() => {
            Swal.fire({
              title: "Log out?",
              text: "Are you sure you want to log out?",
              icon: "warning",
              showCancelButton: true,
              confirmButtonColor: "#ef4444",
              cancelButtonColor: "#6b7280",
              confirmButtonText: "Yes, log out",
              background: "#1f1f1f",
              color: "#fff",
            }).then((result) => {
              if (result.isConfirmed) {
                localStorage.removeItem("user");
                navigate("/login");
              }
            });
          }}
          className="text-red-400 hover:text-red-300 transition"
        >
          Logout
        </button>
      </motion.div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        ref={reportRef}
        className="max-w-2xl mx-auto bg-[#111] p-8 rounded-xl shadow-xl border border-white/10 text-sm leading-relaxed text-gray-200"
      >
        <header className="text-center mb-6">
          <h1 className="text-3xl font-bold text-pink-500">🧠 Preliminary Medical Report</h1>
          <p className="text-xs italic text-gray-400 mt-2">
            Generated by HimalAI for <strong>{patientName}</strong> on {reportDate}
          </p>
        </header>

        <div className="prose prose-invert max-w-none" dangerouslySetInnerHTML={{ __html: sectionedHTML }} />

        <footer className="mt-6 text-center text-xs text-gray-500">
          <p className="italic">📌 This is a preliminary report. All recommendations are assistive and must be verified clinically.</p>
        </footer>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mt-10"
      >
        <button
          onClick={handleDownloadPDF}
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-purple-600 to-pink-600 hover:opacity-90 transition text-sm shadow-md"
        >
          <FiDownload /> Download PDF
        </button>
        <p className="text-xs text-gray-500 mt-3 italic">
          📄 Styled for clarity • 💡 Designed for medical decision-making
        </p>
      </motion.div>
    </div>
  );
}
