import { motion } from "framer-motion";
import { FiDownload } from "react-icons/fi";
import { useNavigate } from "react-router-dom";

export default function ReportScreen() {
  const navigate = useNavigate();

  const summary = `Headache for 2 days with photophobia, BP high. History of migraines.`;
  const diagnosis = ["Migraine", "Subarachnoid Hemorrhage (SAH)"];
  const prescriptions = ["NSAIDs", "Sumatriptan"];
  const treatments = ["CT scan", "Neurology referral"];

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white px-4 py-8 relative overflow-hidden">
      {/* Glow background */}
      <div className="absolute top-0 left-0 w-48 h-48 bg-purple-700 blur-3xl opacity-20 rounded-full animate-float-slow" />
      <div className="absolute bottom-0 right-0 w-32 h-32 bg-pink-500 blur-2xl opacity-10 rounded-full animate-float-slow" />

      {/* Tabs */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex justify-center gap-10 text-sm text-gray-400 mb-10 border-b border-white/10 pb-2 w-full max-w-3xl mx-auto z-10"
      >
        <button onClick={() => navigate("/chat")} className="hover:text-white transition">Chat</button>
        <button className="border-b-2 border-white text-white pb-1">Report</button>
      </motion.div>

      <motion.h1
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-3xl md:text-4xl font-bold text-center text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-500 mb-10"
      >
        🧠 AI Medical Report
      </motion.h1>

      {/* Summary Section */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-white/5 backdrop-blur-md rounded-xl p-6 mb-8 border border-white/10 max-w-3xl mx-auto"
      >
        <h2 className="text-xl font-semibold text-purple-300 mb-2">📝 Patient Summary</h2>
        <p className="text-gray-300 italic">{summary}</p>
      </motion.div>

      {/* Diagnosis Section */}
      <motion.div
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        className="bg-white/5 backdrop-blur-md rounded-xl p-6 mb-8 border border-white/10 max-w-3xl mx-auto"
      >
        <h2 className="text-xl font-semibold text-purple-300 mb-3">🧠 Diagnosis</h2>
        <ul className="list-disc list-inside text-gray-300 space-y-1">
          {diagnosis.map((item, i) => (
            <li key={i}>{item}</li>
          ))}
        </ul>
      </motion.div>

      {/* Prescription Section */}
      <motion.div
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        className="bg-white/5 backdrop-blur-md rounded-xl p-6 mb-8 border border-white/10 max-w-3xl mx-auto"
      >
        <h2 className="text-xl font-semibold text-purple-300 mb-3">💊 Prescription</h2>
        <ul className="list-disc list-inside text-gray-300 space-y-1">
          {prescriptions.map((item, i) => (
            <li key={i}>{item}</li>
          ))}
        </ul>
      </motion.div>

      {/* Treatment Plan */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white/5 backdrop-blur-md rounded-xl p-6 border border-white/10 max-w-3xl mx-auto"
      >
        <h2 className="text-xl font-semibold text-purple-300 mb-3">📈 Treatment Plan</h2>
        <ol className="list-decimal list-inside text-gray-300 space-y-1">
          {treatments.map((step, i) => (
            <li key={i}>{step}</li>
          ))}
        </ol>
      </motion.div>

      {/* Footer / Download */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mt-10"
      >
        <button className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-gradient-to-r from-purple-600 to-pink-600 hover:opacity-90 transition text-sm">
          <FiDownload /> Download PDF
        </button>
        <p className="text-xs text-gray-500 mt-2 italic">
          Generated by HimalAI. AI reports are suggestive. Please verify clinically.
        </p>
      </motion.div>
    </div>
  );
}
